language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
install:
  - python -m pip install --upgrade pip
  - python setup.py install
  - python -m pip install -r unittests/requirements.txt
before_script:
  - python unittests/mock_servers/good_mock_server_v1.py &
  - python unittests/mock_servers/good_mock_server_v2.py &
  - python unittests/mock_servers/bad_mock_server_v1.py &
  - python unittests/mock_servers/bad_mock_server_v2.py &
script:
  - pytest --cov=compliance_suite/ --cov-report=term-missing unittests/
after_success:
  - coveralls
after_script:
  - kill %1 %2 %3 %4