site_name: Compliance Documentation
site_description: Compliance Documentation for refget API Servers
site_author: GA4GH

repo_url: https://github.com/ga4gh/refget-compliance-suite/

nav:
    - 'Preamble': 'index.md'
    - 'API Specification': 'api_spec.md'
    - 'Test Sequences': 'test_sequences.md'
    - 'GET Sequence API':
        - 'Success Conditions': 'GET_sequence_API/success.md'
        - 'Error Conditions': 'GET_sequence_API/errors.md'
    - 'GET Metadata API': 'metadata.md'
    - 'GET service-info API': 'service_info.md'
    - 'Compliance Utility Report system': 'utility.md'

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list

extra_css:
    - css/extra.css

theme:
  name: 'readthedocs'
