OUTPUT_JSON_PATH = "output/server.json"
WEB_DIR = "web"
WEB_DIR_ARCHIVE = "web_0.tar.gz"
GOOD_SERVER_URL = "http://0.0.0.0:8989/"
BAD_SERVER_URL = "http://0.0.0.0:8988/"
JSON_REPORT = "test_report.json"
WEB_FILE_PATH = "test_web"